# Generated by Django 3.1.3 on 2020-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('price', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(related_name='products', to='products.Category')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
    ]
